# Generated by Django 5.0.2 on 2024-02-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_contributor_book_bookcontributor_book_contributors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcontributor",
            name="role",
            field=models.CharField(
                choices=[
                    ("AUT", "Author"),
                    ("COA", "Co-Author"),
                    ("EDT", "Editor"),
                    ("REV", "Reviewer"),
                    ("OTH", "Other"),
                    ("TRA", "Translator"),
                ],
                max_length=20,
                verbose_name="Contribution Role",
            ),
        ),
    ]
